from enum import Enum

"""
现货交易对
"""
class OKXSpotTradingPairs(Enum):
    BTC = "BTC/USDT"
    ETH = "ETH/USDT"
    DOGE = "DOGE/USDT"
    XRP = "XRP/USDT"
    SOL = "SOL/USDT"
    SUI = "SUI/USDT"
    ADA = "ADA/USDT"
    PEPE = "PEPE/USDT"
    SONIC = "SONIC/USDT"
    PNUT = "PNUT/USDT"
    PENGU = "PENGU/USDT"
    WLD = "WLD/USDT"
    MAJOR = "MAJOR/USDT"
    USDC = "USDC/USDT"
    TON = "TON/USDT"
    FIL = "FIL/USDT"
    ACT = "ACT/USDT"
    SHIB = "SHIB/USDT"
    LTC = "LTC/USDT"
    BIO = "BIO/USDT"
    HBAR = "HBAR/USDT"
    TRX = "TRX/USDT"
    ONDO = "ONDO/USDT"
    XLM = "XLM/USDT"
    MOVE = "MOVE/USDT"
    FET = "FET/USDT"

"""
永续合约交易对
"""
class OKXPerpetualSwapTradingPairs(Enum):
    BTC = "BTC-USDT-SWAP"
    ETH = "ETH-USDT-SWAP"
    DOGE = "DOGE-USDT-SWAP"
    XRP = "XRP-USDT-SWAP"
    SOL = "SOL-USDT-SWAP"
    SUI = "SUI-USDT-SWAP"
    ADA = "ADA-USDT-SWAP"
    PEPE = "PEPE-USDT-SWAP"
    SONIC = "SONIC-USDT-SWAP"
    PNUT = "PNUT-USDT-SWAP"
    PENGU = "PENGU-USDT-SWAP"
    WLD = "WLD-USDT-SWAP"
    MAJOR = "MAJOR-USDT-SWAP"
    USDC = "USDC-USDT-SWAP"
    TON = "TON-USDT-SWAP"
    FIL = "FIL-USDT-SWAP"
    ACT = "ACT-USDT-SWAP"
    SHIB = "SHIB-USDT-SWAP"
    LTC = "LTC-USDT-SWAP"
    BIO = "BIO-USDT-SWAP"
    HBAR = "HBAR-USDT-SWAP"
    TRX = "TRX-USDT-SWAP"
    ONDO = "ONDO-USDT-SWAP"
    XLM = "XLM-USDT-SWAP"
    MOVE = "MOVE-USDT-SWAP"
    FET = "FET-USDT-SWAP"
